name: ci

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: shefeekar  # Replace with your Docker Hub username
  CLIENT_IMAGE: blog-app-client  # Frontend image name
  SERVER_IMAGE: blog-app-server  # Backend image name

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Use `secrets` if username is sensitive
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and Push Client (Frontend)
      - name: Build and Push Client Image
        uses: docker/build-push-action@v6
        with:
          context: ./client  # Path to client directory
          file: ./client/Dockerfile  # Explicitly specify Dockerfile location
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.CLIENT_IMAGE }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.CLIENT_IMAGE }}:${{ github.sha }}

      # Build and Push Server (Backend)
      - name: Build and Push Server Image
        uses: docker/build-push-action@v6
        with:
          context: ./server  # Path to server directory
          file: ./server/Dockerfile  # Explicitly specify Dockerfile location
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_IMAGE }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_IMAGE }}:${{ github.sha }}
